### ISSUE TITLE
Was macht der genau?

### ISSUE THREAD

**Issue by supertobi** [NikolaiRadke/NOKOlino#1]
Mir fehlt eine Beschreibung, was das Monster denn jetzt macht.  
Wenn ich den Quellcode richtig verstehe wird ca. alle 10 Minuten eine zufällige Datei abgespielt und eine spezielle beim drücken des Button. Ist das richtig so?

**Comment by NikolaiRadke** [comment]
Genau.
Und wenn der Akku zuneige geht, sagt er "Piep". Ansonsten frisst er Strom :-) 
Vielleicht sollte ich das im Wiki etwas deutlicher machen.

**Comment by supertobi** [comment]
Ja, bitte.

**Comment by NikolaiRadke** [comment]
Ist erledigt :-)

LG
