### ISSUE TITLE
Fehler beim Bootloader frashen

### ISSUE THREAD

**Issue by AntoniusOD** [NikolaiRadke/NOKOlino#17]
Mein Sohn und ich versuchen dein tolles Projekt nachzubauen. Heute haben wir damit angefangen und sind bis zum ersten flashen gekommen. 
Wenn wir das Bootloader brennen auslösen, erhalten wir die Fehlermeldung:

avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
         Double check connections and try again, or use -F to override
         this check.

Wir verwenden einen ELEGOO MEGA2560 R3 und einen attiny85-20 pu, die Verdrahtung habe ich mehrfach überprüft. Was können wir noch überprüfen?

**Comment by NikolaiRadke** [comment]
0x000000 bedeutet, dass gar nix gefunden wurde, also die Verbindung nicht hinhaut. Kein Wunder, denn die Verkabelung für einen Mega ist anders:

Attiny -> Mega
Pin 1 -> Pin 53
Pin 2 -> leer
Pin 3 -> leer
Pin 4 -> GND

Pin 8 -> 5V
Pin 7 -> Pin 52
Pin 6 -> Pin 50
Pin 5 -> Pin 51

Den Elko nicht vergessen.
Viel Erfolg!

**Comment by NikolaiRadke** [comment]
Gerne. 
Der Elko verhindert, dass der Arduino automatisch einen Reset während des Beschreibens durchführt, der hardwareseitig ausgelöst wird. Er dient sozusagen als Puffer für das Signal.

**Comment by NikolaiRadke** [comment]
Foto an mich nicht vergessen! 
:-D

**Comment by mettmaniac** [comment]
Nachdem ich hier grade Stunden mit einem RobotDyn MegaR3 verbracht habe und schon echt alles moegliche vermutet habe (defekte ATTiny85 von AliExpress geliefert bekommen? China-Verbindungskabel kaputt? Elko defekt?), wollte ich kurz darauf hinweisen, dass scheinbar bei einigen Mega-Clonen nicht Pin 53 sondern stattdessen Pin 10 zu verwenden ist. Damit hat es bei mir geklappt :)

Attiny -> Mega
Pin 1 -> Pin **10**
Pin 2 -> leer
Pin 3 -> leer
Pin 4 -> GND

Pin 8 -> 5V
Pin 7 -> Pin 52
Pin 6 -> Pin 50
Pin 5 -> Pin 51

**Comment by NikolaiRadke** [comment]
Danke!  
Ich werde die Belegung für den Mega in das Wiki aufnehmen, zusammen mit beim Hinweis auf Pin 10. Ich kann es mangels Arduino Mega nicht testen. Vielleicht habe ich mal einen, wenn ich groß und reich bin.  

Fragen geklärt? Dann wird hier morgen geschlossen. Das ist wie ToDo-Listen abhaken :-)

**Comment by mettmaniac** [comment]
9 USD bei AliExpress ;)

Von mir aus kann hier zugemacht werden.

**Comment by NikolaiRadke** [comment]
Weiter gehts :-)
