### ISSUE TITLE
JQ6500 Zugriffsfehler

### ISSUE THREAD

**Issue by AntoniusOD** [NikolaiRadke/NOKOlino#21]
Ich hänge beim bespielen des JQ6500 fest. Ich verstehe es so, dass er einfach mit einem USB-Kabel an PC angeschlossen wird und man mit dem kleinen Tool, das auf dem JQ liegt, die MP3-Dateien drauf kopiert. 

Bei mir wird der JQ zwar als CD-Laufwerk erkannt (PuP erkennt das Gerät und installiert die Treiber) , nur kann man nicht darauf zugreifen, es verhält sich wie ein CD Laufwerk ohne CD. 

Ich habe mir das Update Tool aus dem Netz geholt, aber da erhalte ich auch nur einen "flashdata error".
Bisher habe ich es auf verschiedenen PC's  unter Win10 und Win7 mit verschiedenen USB Kabeln/Ports versucht. Letztlich habe ich einen neuen JQ6500-16p V2.1 gekauft - leider mit dem gleichen Resultat.

**Comment by NikolaiRadke** [comment]
Oje - da hast Du keine Chance. Wenn dieses Tool nicht von Haus aus auf dem Modul ist, kann es (momentan) von Windows aus nicht beschrieben werden. 

Bei manchen dieser chinesischen Qualitätsprodukte kommt das leider vor. Unter Linux geht es problemlos. 

Wenn Du kein Linux hast, kann ich Dir nur anbieten, Dir ein bespieltes Modul per Post zu schicken.

**Comment by AntoniusOD** [comment]
Linux habe ich nicht und ich kenne mich mit Linux auch nicht aus, daher würde ich dein Angebot gerne annehmen. Wo soll ich den JQ6500 hinschicken?

**Comment by NikolaiRadke** [comment]
Ich habe eben meine fünf Module unter Windows getestet - keines davon hatte das Tool drauf. Gibt wohl Anbieter (ebay), die Ausschussware verkaufen. Ärgerlich.

Bitte eine Email an kontakt@nikolairadke.de
