### ISSUE TITLE
JQ6500 mit 32MBit und Windows

### ISSUE THREAD

**Issue by NikolaiRadke** [NikolaiRadke/NOKOlino#23]
Leider wird in den meisten Fällen das Modul ohne vorinstallierte Windows-Software ausgeliefert. Es ist nicht möglich, unter Windows die Dateien aufzuspielen, auch nicht, wenn die Software heruntergeladen und manuell gestartet wird, da sie sich auf dem virtuellen Laufwerk befinden muss.

Ich habe ein Mini-Linux (ca. 19 MB) erstellt, mit dem ein bootfähiger USB-Stick erstellt werden kann. Darauf befinden sich auch das Tool und die MP3s zum beschreiben des Moduls. Es funktioniert bereits, aber ich muss es noch für Neulinge komfortabler machen.

**Comment by NikolaiRadke** [comment]
Offenbar betrifft das beinahe alle 32MBit-Modelle. Sie können nicht unter Windows bespielt werden. Mit dem Image, zu dem in Kürze (morgen?) die Anleitung folgt, ist es nun Möglich, eine angepasste Software auf das Modul zu schreiben und den Upload auch unter Windows vorzunehmen.

Abwarten, alles wird gut :-)

**Comment by NikolaiRadke** [comment]
Fertig!

Ich habe ein neues Repository erstellt, in dem ein bootfähiges ISO-Image (20 MB!) bereitgestellt wird, das Module ohne Uploadsoftware repariert: [JQ6500_rescue_tool](https://github.com/NikolaiRadke/JQ6500-rescue-tool)  
  
Perfekt für Windows-Nutzer ohne Lust, sich in Linux einzuarbeiten (was ich aber grundsätzlich empfehle... ;-) )  
  
Viel Spaß!

**Comment by ripe-banana** [comment]
Ich habe ein 16MBit Modell (JQ6500-16P v2.1). Dieses wurde auch ohne Windows-Oberfläche ausgeliefert.

- Erster Versuch (fehlgeschlagen): Linux tool von Reinhard Max hat Modul eigentlich erkannt, jedoch bei der Durchführung mit Fehler abgebrochen.
- Zweiter Versuch (fehlgschlagen): Rescue tool (Version vom 28.03.2018) hat Modul nicht erkannt.
- Dritter Versuch (erfolgreich): Auf [Gogo_Tronics](https://sparks.gogo.co.nz/jq6500/index.html) unter _"Or if you are really stuck you can download this zip file [...]"_ habe ich dieses File gefunden: [JQ6500_voice_chip_module.zip](https://sparks.gogo.co.nz/assets/_site_/downloads/JQ6500_voice_chip_module.zip). Die Ausführung in Windows per command line von mydown.bat hat schließlich die Windows-Oberfläche problemlos auf das Modul geflashed.

Kann man letztere Variante evtl. in das Wiki (Seite: "MP3s aufspielen") aufnehmen?

**Comment by NikolaiRadke** [comment]
Hallo!

Sorry für die späte Antwort, habe ich glatt übersehen. Danke für den Hinweis!
Reinhard hat das Tool überarbeitet und ich werde das ISO neu anpassen.

Hast Du Windows 10? Ich habe mydown.bat da ums Verrecken nicht zum laufen bekommen, daher habe ich überhaupt das ISO erstellt. Ich werde es aber nochmal probieren. Bin ja jetzt ermutigt. Das Wiki wird natürlich entsprechend überarbeitet (Das wird eh mal wieder Zeit).

Liebe Grüße,

Nikolai
