### ISSUE TITLE
Leiterplatte

### ISSUE THREAD

**Issue by NikolaiRadke** [NikolaiRadke/NOKOlino#6]
Der Entwurf ist natürlich schick, aber wäre dann noch Platz oberhalb des TP für den Lautsprecher? Unten kommt nicht in Frage, das klingt grauenhaft. Wenn ja, hätte es den Vorteil, dass der Akku unten auch eine andere Bauweise haben könnte. 

Wäre es möglich, das MP3-Modul um 180 Grad zu drehen? Sollte das Innenleben als Spielwerk verwendet werden, kann so leicht ein neues Lied aufgespielt werden.

Vielen Dank schon mal für die Mühe!

LG,
Nikolai

**Comment by Crayfish68** [comment]
Hallo Nikolai

Jawoll. Ich habe die Leiterplatte auf 5cm x 5cm gebracht, passt mal wieder alles gerade so drauf :)
Auf diese Art können wir dann beim Hersteller auf einer Leiterplatte von 10cm x 10cm jeweils 4 unterbringen. Wenn wir davon dann 10 bestellen, haben wir 40 Boards. Sollte erst einmal reichen.* Preislich wären wir dann irgendwo bei 1,20€ für das Board ([16.42 + 29.91 shipping] /40 = 1,16€, wenn kein Zoll dazu kommt). 

Ich habe wieder USB Pins für das MP3 Modul angelegt, die werden dann zum USB Anschluss geroutet.

Ich habe alle Module so weit wie möglich an den Rand geschoben, um möglichst viel Platz für den Lautsprecher zu schaffen. Der Lautsprecher ragt dann nur teilweise (6,7mm) über das MP3 Modul, was ja relativ flach ist.
Wenn du Platz für den ganzen Lautsprecher haben möchtest, dann müsste das Board größer gemacht werden (z.B. 5cm x 6cm), auch kein Problem. Dann wird es vielleicht etwas teurer ... nagut, sind dann vielleicht 2€, auch kein Drama.
Kannst du noch mal BxHxL von deinem Akku sagen? Vielleicht macht es Sinn, Lautsprecher und Akku nebeneinander auf eine Platine zu bringen und dann diese Platine darunter? Dann verringert sich die Gesamthöhe noch einmal deutlich.

vG
Crayfish

*es wurde schon für den nächsten Kindergeburtstag dieses Projekt angefragt - wenn das alles so klappt, würde ich dann ca. 10 nehmen - dauert aber noch, September...

**Comment by Crayfish68** [comment]
Dank "Frederike" geht es schon hier weiter:

Die Idee war jetzt, genug Platz für den Lautsprecher zu schaffen. Er bekommt auch direkt die passenden Befestigungslöcher, so kann er auf der Hauptplatine mit M2 Schrauben befestigt werden (strahlt natürlich nach oben), bekommt dort auch gleich seine zwei Pins, so das er nicht über irgendwelche Stecker angeschlossen werden muss.
Damit das passt, musste ich die Leiterplatte 5cm x 6cm machen. Preislich macht das nur minimal Unterschied.

Als Stecker müssen wir gewinkelte nehmen:  gerade Stecker stünden ja hoch und passen daher nicht. Ich habe die Footprints mal entsprechend angepasst und auch die 3D Models dafür gefunden.

So sieht es jetzt aus in der 5x6cm Version:
![bildschirmfoto vom 2018-01-18 21-47-37](https://user-images.githubusercontent.com/22168209/35120681-3b369d08-fc99-11e7-86ea-e608493046b3.png)
Hier mal ein 3D Eindruck:
![nokolino_pcb_3d_front](https://user-images.githubusercontent.com/22168209/35120715-564ddf34-fc99-11e7-8bb6-b7f617a4ed79.png)

Alternativ hätte ich auch eine 5x5cm Variante anzubieten:
![bildschirmfoto vom 2018-01-18 10-08-36](https://user-images.githubusercontent.com/22168209/35120796-94fe5a56-fc99-11e7-9eb6-1cdcb5bd8544.png)
da hatte ich jetzt noch nicht die gewinkelten Stecker, aber es geht ja nur darum zu zeigen, wie der Lautsprecher über das TP Modul drüber ragen würde. Der Lautsprecher müsste dann an die obere Platte angebracht werden.

Ist beides machbar. Ich persönlich finde die 5x6cm Variante schicker, aber vielleicht übersehe ich ja irgendwas.

vG
Crayfish

**Comment by NikolaiRadke** [comment]
Frederike und NOKOlino sind eindeutig Freunde :-)

Der Lautsprecher muss unbedingt an die obere Platte angebracht werden, um einen akustischen Kurzschluss zu vermeiden. Wäre er unten, klänge es schrecklich. 

Auch frage ich mich, ob wir Stecker brauchen. Das Crimpen ist aufwändiger, als diese paar Kabel anzulöten, oder? Dann wäre auch Platz für einen (gewinkelten?) USB-Stecker für das MP3-Modul, um D+ und D- herausführen zu können.

Wenn der Preisunterschied so minimal ist, dann ziehe ich 5x6cm vor, da es so auch mehr Auswahlmöglichkeiten für den Akku gibt.

LG
Nikolai

**Comment by Crayfish68** [comment]
Das mit dem akustischen Kurzschluss wusste ich natürlich sofort - wollte nur testen, ob du auch aufpasst!

;)

Ja, Stecker ist schon irgendwie total overkill. Kann es sein, dass NOKOlino ein heimlicher Streber ist!?
Nunja, so haben alle alle (!?) Optionen, können entweder Stecker kaufen, oder auch nicht. Wenn sonst nichts dagegen spricht, lasse ich sie so.

Dann nehme ich die Befestigungs-Löcher aus dem Lautsprecherfootprint wieder raus, lasse aber die Lötaugen drin, dann kann er da direkt angeschlossen werden.
Ich schiebe auch noch das MP3 Modul so weit runter, das möglichst viel Platz für einen USB Stecker da ist. Vielleicht magst du das dann mal ausdrucken, die Module (MP3 Modul, ich habe noch keins), und die Taster rauflegen und gucken, ob wir die Größe eines fertig konfektionierten USB Steckers da nicht unterschätzen? Und ob die Richtung stimmt?! Ich hatte an meine "Selbstlötstecker" gedacht, die passen da locker hin, aber normale, speziell die gewinkelten, sind im Vergleich dazu 'riesig'. Zumindest kommt es mir so vor.
Ich gucke mal, ob ich es in ein PDF drucken kann und werde es dir dann schicken, zum ausrucken.

Noch eine Frage: was hast du eigentlich als Kappen für die Taster in Richtung obere Platine genommen? Gab es diese Kappen zu den Tastern dazu? Ich habe Schwierigkeiten welche zu finden, die Online Kataloge sind Datengräber :/

**Comment by NikolaiRadke** [comment]
Die Kappen nennen sich "Tastkappen". Sowas hier z.B.:
https://www.conrad.de/de/tastkappe-gelb-diptronics-ktsc-61y-1-st-705361.html

PDF wäre praktisch, dann probiere ich das mal aus.

**Comment by Crayfish68** [comment]
PDF kommt mit dem nächsten Pull, ein Request müsste bei dir noch liegen, oder?

Obere Leiterplatte kommt auch demnächst...

vG
Crayfish

**Comment by NikolaiRadke** [comment]
Ne, den Request hast Du Dir ins eigene Repository gesetzt :-)

**Comment by NikolaiRadke** [comment]
Sehr schick, die obere Platte
 Aber ich glaube, das ist vielleicht zu instabil, da ja genau dort mit den (brutalen!Kinder-) Händen gedrückt wird, oder?

**Comment by Crayfish68** [comment]
Mh, da magst du recht haben. Im PCB Editor sieht das immer alles super aus.
Mach mal n Vorschlag! Vielleicht mit Löchern? Oder die Schlitze 1mm und die Stege auch 1mm? 2mm?
Ich habe schon erfolglos nach Ideen bei Google gesucht - stehe grad irgendwie noch auf dem Schlauch. Bräuchte mal wieder eine kreative Phase...

vG
Crayfish

**Comment by NikolaiRadke** [comment]
Ich glaube, Du bist da einfach zu akribisch :-)
Bei mir sieht das so aus:
![loecher](https://user-images.githubusercontent.com/16576820/35294928-11246f26-0078-11e8-8f53-0fbb97184528.jpg)

**Comment by NikolaiRadke** [comment]
Ich denke, ein paar Löcher reichen locker, ggf. auch streifen mit einigen Millimeter Stärke und Abstand.

**Comment by Crayfish68** [comment]
Naja, ich hab es gerne immer so schick es geht ;)


Neuer Versuch: Breite der Schlitze ist jetzt 2,5mm, dazwischen jeweils 2mm Steg, mit nochmal 4 Querstegen. Sollte in jedem Fall stabiler sein, als die Lochrasterplatte. Da ist ja auch noch Kupfer oben und unten drauf.

![top pcb 3d](https://user-images.githubusercontent.com/22168209/35476225-98b8439a-03ac-11e8-98ee-b506656bc2ba.png)

PDF als Größenabgleichsausdruckdokument hängt auch an.


vG
Crayfish
[Ausgabe.pdf](https://github.com/NikolaiRadke/NOKOlino/files/1670513/Ausgabe.pdf)

**Comment by NikolaiRadke** [comment]
Habs getestet, passt super. Jetzt bitte noch das Logo tauschen und mir erklären, wie zwei Platinen in eine Bestellung kommen, dann geht der Auftrag nach Fernost :-)

**Comment by Crayfish68** [comment]
Die Logos sollten stimmen.

Ich habe hier noch ein kleines Problem: der PCB Hersteller nimmt keine Orders an, wenn kein Drill File dabei ist. Ich habe jetzt einfach "Fake" Lötpunkte gesetzt. Ich habe mir gedacht, ich setze sie genau mittig dort, wo unten die Taster sind. Dann kann man es vielleicht besser ausrichten, oder vielleicht mit einem Schräubchen die Taster fixieren (wenn der Kleber nicht hält), oder aufbohren und dann die Taster reinkleben, oder ... oder ..., ...

Spricht was dagegen?
![kicad_top_pcb](https://user-images.githubusercontent.com/22168209/35486570-ebd46284-046f-11e8-97de-aad2914c1481.png)

**Comment by Crayfish68** [comment]
Also, passend zu dem "jetzt können wir ordern" hat easyeda natürlich ihre Webseite geändert und jetzt (wie allerdings bereits angedroht) zu jlcpcb.com umgeschaltet. Außerdem feiern sie Chinese New Year vom 10.2 bis 23.2. (!!), es könnte sich also alles ein bischen verzögern.
Das sollten allerdings keine grundsätzliche Hindernisse sein. Also, ich würde denken (nachdem du gepullt hast) gehst du folgendermaßen vor:

1. auf jlcpcb.com einen Account anlegen
2. die NOKOlino/schematics/kicad/GERBERS/NOKOlino_Gerbers.zip hochladen
 a.  Breite/Länge sollte sich automatisch auf 60/50 stellen
 b. Bei "Panel By JLCPCB" auf "Yes" und dann "2" und "2" in die Boxen (dann bekommen wir 10 boards, auf denen jeweils 4 break away boards sind, so verstehe ich das jedenfalls)
 c. Save to Cart
3. dasselbe dann noch einmal mit NOKOlino/schematics/kicad_top_pcb/GERBERS/kicad_top_pcb.zip
4. dann solltest du beide im Cart haben und zur Kasse gehen, dort wird dann Shipping draufgelegt.

Order Alternative 1:
- Preis für 4 x 10 = 40 PCBs ist $27,81
- Shipping ist $26,68
- macht zusammen $82,30.
- geteilt durch 40, dann landen wir pro Satz (eine obere, eine untere PCB) bei $2,05.

Order Alternative 2:
- Preis für 10 x 1 = 10 PCBs ist $2
- Shipping ist $22,08
- macht zusammen $26,08
- geteilt durch 10, dann landen wir pro Satz (eine obere, eine untere PCB) bei $2,60.

Wenn noch irgendwas nicht stimmt mit den Leiterplatten, dann hast du bei der Alternative 1 einen ziemlich großen haufen Müll :/

Vielleicht gibt es noch andere Kombinationen, die dass noch günstiger macht. Ich habe jetzt nichts anderes mehr durchprobiert.

Augen zu und durch! Hoffentlich klappt diesmal alles auf Anhieb!!

vG
Crayfish
PS: der GERBER Viewer auf deren Webseite zeit die Schrift auf der Rückseite des Boards spiegelverkehrt an. Bei mir in KiCad sieht es allerdings richtig aus.

**Comment by NikolaiRadke** [comment]
Uiuiuiui - ich habe mich für Alternative 2 entschieden, weil dann keine Steuern anfallen. Hauptsache, die Platinen kommen vor dem Neujahr, da geht echt wochenlang nix. 

Komisch, dass mir trotz DHL Express nur 9$ berechnet wurden...

**Comment by NikolaiRadke** [comment]
Die Platinen sind heute in Berlin angekommen. Montag sind sie da :-)

**Comment by Crayfish68** [comment]
Tschakka!! Ich liebe parallele Projekte :/

Bin eh bis nächste Woche in Ö, lass dir also Zeit!

Von meinem iPhone gesendet

**Comment by NikolaiRadke** [comment]
Schade, die Platinen sind leider unbrauchbar. Die Taster sind falsch beschaltet, sie müssten um 90 Grad gedreht werden. Auch ein zurechtbiegen der Beine wird nicht helfen, da sie ja exakt eben auf der Platine sitzen müssen, um die obere Platine zu halten.

Naja, 9€ Lehrgeld und ein paar verplemperte Bauteile.

**Comment by Crayfish68** [comment]
Sch.......!!!!

**Comment by NikolaiRadke** [comment]
Ja nu - keine 15€ verballert. Schade ist es höchstens um die Zeit, aber ich habe es auch nicht wirklich eilig :-)

**Comment by Crayfish68** [comment]
Schick mir trotzdem mal 2 bitte, dann guck ich mir das an. Ärgerlich :(

**Comment by NikolaiRadke** [comment]
Klar, mach ich gern.
Auf Anhieb ist doch nie was fehlerfrei. Nächste Version wird super :-)

**Comment by Crayfish68** [comment]
Kannst du mir auch noch bitte die genaue Bezeichnung (am besten einen Link) zu den Tastern geben, die du verwendest? Im Idealfall bräuchte ich das Datenblatt. Welche Höhe an Tastern verwendest du?

**Comment by NikolaiRadke** [comment]
Fazit:
