### ISSUE TITLE
Akku / Batterie

### ISSUE THREAD

**Issue by Crayfish68** [NikolaiRadke/NOKOlino#9]
Vielleicht noch ein Issue zum Thema Akku?

Ich habe mal nach Batterien / Akkus geschaut (sitze immer noch fest, daher habe ich Lagenw.... äähh ... ich meinte Zeit!) Ich finde diese flachen LiPos ziemlich praktisch. In der Größe 5x6cm gibt es z.B. diesen hier:

![grafik](https://user-images.githubusercontent.com/22168209/35142949-35eb4152-fd00-11e7-9187-62c4798aacec.png)

Müsste man eben rechtzeitig bestellen, dauert etwa 30 Tage, bis das Zeugs hier an kommt. Diesen Akku könnte man aber schön flach, doppelseitiges Klebeband oder Powerstrip, an das NOKOlino-Paket anbringen. Er ist nur 3,8mm dick!
Dieser Lieferant hat so ziemlich alle Größen und Formen, in meinen NOKOs tun dies Akkus ihren Dienst bis jetzt ohne Ausfälle.

vG
Crayfish

**Comment by NikolaiRadke** [comment]
Ja, solche ähnlichen Akkus verwende ich ja in NOKO.
Ich habe mich für den etwas höheren entschieden, weil die schnell und reichlich für ähnlich kleines Geld verfügbar sind. Aber bei einer 5x6cm-Platine hat der geneigte Bastler ja dann mehr Wahlfreiheit :-)
